### ISSUE TITLE
svn mirror

### ISSUE THREAD

**Issue by stefankueng** [oxc/kolmafia#1]
If possible, could you document on how you set up the svn mirror?

**Comment by oxc** [comment]
Sure, it's all more or less self-documented in the [mirror-upstream.yml](https://github.com/oxc/kolmafia/blob/main/.github/workflows/mirror-upstream.yml) github action.

I've added a [separate update check](https://github.com/oxc/kolmafia/blob/1fa5b615f6eb7942ae003a93c4deb0cdcc907bc2/.github/workflows/mirror-upstream.yml#L13), which runs way quicker than checking out the whole repository, but that's not strictly necessary. The main work is done in the [fetch_changes](https://github.com/oxc/kolmafia/blob/1fa5b615f6eb7942ae003a93c4deb0cdcc907bc2/.github/workflows/mirror-upstream.yml#L68) job.

The tricky part is that a) KoLmafia requires the git-svn information, and b) without the git-svn information the update takes way to long. To solve this, I have (manually once) committed the `.git/svn` directory to a completely separate branch. It's [checked out](https://github.com/oxc/kolmafia/blob/1fa5b615f6eb7942ae003a93c4deb0cdcc907bc2/.github/workflows/mirror-upstream.yml#L89) separately in the mirroring process, and changes are [committed back](https://github.com/oxc/kolmafia/blob/1fa5b615f6eb7942ae003a93c4deb0cdcc907bc2/.github/workflows/mirror-upstream.yml#L105).

Does this answer your question?

**Comment by stefankueng** [comment]
not quite. I've of course checked the mirror-upstream.yml file before asking here.
What I don't understand is how you've set up the mirror from scratch.
I've tried to do it myself, but I always end up with a different layout than you. For example, in your [git-svn](https://github.com/oxc/kolmafia/tree/svn-meta/refs/remotes/git-svn) folder there are only three files. But when I create an 'svn git init', 'svn git fetch' repository I have not three files in there but a ref/remotes/origin folder with many folders representing the svn branches/tags in there.
So what I'm interested in is how you actually set this up so your yml script can work.

**Comment by oxc** [comment]
Just use your git-svn folder then. I think at some point I had to re-create mine, because I accidentally deleted it. 

Basically, as far as I can remember (and what makes sense to me), what I did is:

```
# main code
git svn clone https://svn.code.sf.net/p/kolmafia/code
git remote add origin git@github.com:oxc/kolmafia.git
git checkout -b upstream
git push --set-upstream origin upstream

# svn meta
cd .git/svn
git init
git remote add origin git@github.com:oxc/kolmafia.git
git checkout -b svn-meta
cp ../refs/remotes/git-svn stored-ref
git add .
git commit -m 'Initial svn-meta commit'
git push --set-upstream origin svn-meta
```

I have not tested these commands, but it should more or less work this way.

Of course, if you want to use this for KoLmafia, you can also just clone my repository and continue from there.

**Comment by stefankueng** [comment]
Thanks! That should be enough for me to get this working.

**Comment by oxc** [comment]
Let me know if you get stuck somewhere.

**Comment by stefankueng** [comment]
one thing left: how to get the changes done on `upstream` back to the main branch? Best done in the action file?

**Comment by oxc** [comment]
I was planning to use a repository dispatch to trigger an action that rebases the main branch, just haven't come around to it yet.
